version: "3.4"
services:
  baserow-translate-plugin:
    container_name: baserow-translate-plugin
    image: baserow-translate-plugin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      BASEROW_PUBLIC_URL: http://localhost
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data: